# Generated by Django 5.0 on 2023-12-19 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email_id', models.CharField(max_length=400)),
                ('password', models.CharField(max_length=300)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
