# Generated by Django 5.0 on 2023-12-19 06:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('blog', models.CharField(max_length=4000)),
                ('author', models.CharField(max_length=300)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
